basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a system integration for Macapá and VareJão.
  license: {}
  title: REST API - Macapá and VareJão
  version: "1.0"
paths: {}
swagger: "2.0"
